version: '2'

services:

  speakme:
    build:
      context: ./
      dockerfile: Dockerfile.debug
    environment:
      DEBUG: 1
      NODE_ENV: "development"
      BACKEND_URL: "http://localhost:5081"
    ports:
      - "5080:5080"
      - "5081:5081"
      - "5089:80"
    volumes:
      - ./src:/var/www/src
      - ./theme:/var/www/theme
      - ./webpack.run.js:/var/www/webpack.run.js
      - ./run.sh:/var/www/run.sh
#      - ./mock.server.js:/var/www/mock.server.js
      - ./package.json:/var/www/package.json